'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { ArrowUpRight, BadgeCheck, CalendarDays, Clock3, LogOut, QrCode, UserRound, ClipboardList, CheckCircle2 } from 'lucide-react';
type Profile={id:string;full_name:string|null;role:string;class_name:string|null;is_verified:boolean};
type RecordItem={id:string;attendance_date:string;checked_in_at:string;status:string;attendance_sessions?:{title:string;class_name:string|null}|null};
export default function Dashboard(){
  const [email,setEmail]=useState('');const [profile,setProfile]=useState<Profile|null>(null);const [error,setError]=useState('');const [records,setRecords]=useState<RecordItem[]>([]);const [activeCount,setActiveCount]=useState(0);const router=useRouter();
  useEffect(()=>{(async()=>{if(!supabase){setError('Supabase belum dikonfigurasi. Tambahkan env lalu refresh.');return;}const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setEmail(user.email||'');const {data,error:profileError}=await supabase.from('profiles').select('id,full_name,role,class_name,is_verified').eq('id',user.id).maybeSingle();if(profileError){setError(profileError.message);return;}setProfile(data as Profile|null);const {data:{session}}=await supabase.auth.getSession();const headers={Authorization:`Bearer ${session?.access_token||''}`};const [historyRes,sessionsRes]=await Promise.all([fetch('/api/attendance/history',{headers}),fetch('/api/attendance/sessions',{headers})]);if(historyRes.ok){const r=await historyRes.json();setRecords(r.records||[]);}if(sessionsRes.ok){const r=await sessionsRes.json();setActiveCount((r.sessions||[]).filter((s:{status:string;expires_at:string})=>s.status==='active'&&Date.now()<new Date(s.expires_at).getTime()).length);}})();},[router]);
  async function logout(){await supabase?.auth.signOut();router.push('/login');}
  const admin=profile?.role==='admin';const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const attendedToday=records.some(r=>r.attendance_date===today);
  return <main className="app-shell shell"><header className="app-nav"><Link href="/" className="brand">HADIR<span>!</span></Link><div className="nav-right"><span className="user-chip"><UserRound size={15}/>{profile?.full_name||email||'Memuat akun...'}</span><button className="icon-button" onClick={logout} aria-label="Keluar"><LogOut size={17}/></button></div></header><div className="dashboard-head"><div><div className="eyebrow"><span className="dot"/> DASHBOARD</div><h1>HALO, {(profile?.full_name||'TEMAN').split(' ')[0].toUpperCase()}!</h1><p>Siap mencatat kehadiran hari ini?</p></div></div>{error&&<div className="notice">{error}</div>}<section className="welcome-panel"><div><span className="panel-label">AKUN KAMU</span><h2 className="dashboard-name-line">{profile?.full_name||'Profil siswa'}{admin&&profile?.is_verified&&<BadgeCheck className="verified-check-icon" size={22} aria-label="Terverifikasi" title="Terverifikasi"/>}</h2><p>{admin?'Administrator sekolah':profile?.class_name||'Kelas belum diatur'} · {email}</p><div className="panel-actions"><Link className="button button-small" href="/profile">Lihat profil <ArrowUpRight size={16}/></Link>{admin&&<Link className="button button-small button-light" href="/admin">Panel admin <ArrowUpRight size={16}/></Link>}<Link className="button button-small button-light" href="/attendance/scan"><QrCode size={16}/> Scan absensi</Link></div></div><div className="big-icon"><CalendarDays size={50}/></div></section><section className="stats-grid"><article className="stat-card"><span>STATUS HARI INI</span><strong>{attendedToday?'HADIR':'—'}</strong><small>{attendedToday?'Absensi hari ini sudah tercatat':'Belum ada absensi hari ini'}</small></article><article className="stat-card"><span>TOTAL KEHADIRAN</span><strong>{records.length}</strong><small>Riwayat absensi akun ini</small></article><article className="stat-card"><span>{admin?'SESI AKTIF':'SESI QR AKTIF'}</span><strong>{admin?activeCount:'SCAN'}</strong><small><Clock3 size={14}/> {admin?'QR yang belum kedaluwarsa':'QR dari admin berlaku satu jam'}</small></article></section>
    <section className="scanner-cta"><div className="icon-box"><QrCode/></div><div><h2>{admin?'SCAN ABSENSI (OPSIONAL)':'ABSEN SEKARANG'}</h2><p>{admin?'Admin tidak wajib melakukan scan. Jika admin juga ikut hadir sebagai peserta, scan QR agar kehadirannya tercatat.':'Login dengan akunmu, lalu scan QR yang ditampilkan admin.'} QR hanya berlaku satu jam sejak dibuat.</p></div><Link className="button" href="/attendance/scan">Mulai scan <ArrowUpRight size={16}/></Link></section>
    <section className="student-list"><h2><ClipboardList size={22}/> Riwayat kehadiran</h2>{records.length===0?<p className="muted">Belum ada catatan absensi. Setelah melakukan scan, riwayat akan muncul di sini.</p>:records.map(r=><article key={r.id} className="student-row"><div><b>{r.attendance_sessions?.title||'Absensi sekolah'}</b><small>{r.attendance_date} · {new Date(r.checked_in_at).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'})} WIB</small></div><span className="role-admin"><CheckCircle2 size={14}/> HADIR</span></article>)}</section><button className="text-button" onClick={logout}>Keluar dari akun <LogOut size={15}/></button></main>;
}
